name: yolo-seg-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - ultralytics==8.3.0
      - opencv-python-headless
      - pillow
      - numpy
      - azureml-inference-server-http
